apiVersion: v1
kind: Secret
metadata:
  name: acr-creds
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JkZXYuYWNyb3NvZnRmb250b2RvYXBwMDEuYXp1cmVjcm8uaW8iOnsidXNlcm5hbWUiOiJhY3JkZXYuZnJvbnR0b2RvYXBwMDEiLCJwYXNzd29yZCI6ImQyUVV6S29JcVBVaFRZZHN1MnFXQmZxQXlneTh5cm9vVk5oV3MrZGpKYiswQUNSRC9CMXNzMyIsImF1dGgiOiJkMlFVenRLaUlcL1BVaFRZZHN1MnFXQmZxQXlneTh5cm9vVk5oV3MrZGpKYiswQUNSRC9CMXNzMyJ9fX0=
